# This is a basic workflow to help you get started with Actions

name: Test Graph PowerShell

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Run a command to check PowerShell version
      - name: Check PowerShell version
        shell: pwsh
        run: Write-Host $PSVersionTable.PSVersion

      # Run a command to install Microsoft Graph PowerShell (without cache)
      - name: Install Microsoft Graph PowerShell
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Microsoft.Graph -Scope CurrentUser
      
      # Run a command to check the Graph PowerShell version
      - name: Check the Graph PowerShell version
        shell: pwsh
        run: Get-InstalledModule Microsoft.Graph

      # Try a command that does not need to connect
      - name: Try a command that does not need to run the Connect-MgGraph
        shell: pwsh
        run: Find-MgGraphCommand -command Get-MgUser

      # Coonect
      - name: Run the the Connect-MgGraph
        shell: pwsh
        env:
          TenantId: ${{ secrets.TenantId }}
          AppId: ${{ secrets.AppId }}
          AppSec: ${{ secrets.AppSec }}
        run: |
          Write-Host "$env:TenantId"
          Write-Host "$env:AppId"

        
