# This is a basic workflow to help you get started with Actions

name: Test Graph PowerShell

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Run a command to check PowerShell version
      - name: Check PowerShell version
        shell: pwsh
        run: Write-Host $PSVersionTable.PSVersion

      # Coonect
      - name: Connect run the code and disconnect
        shell: pwsh
        env:
          TenantId: ${{ secrets.TenantId }}
          AppId: ${{ secrets.AppId }}
          AppSec: ${{ secrets.AppSec }}
          WebAppId: ${{ vars.WebAppId }}
        run: |
          Write-Host "Web application ID 1: " ${{ env.WebAppId }}

          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Microsoft.Graph.Beta -Scope CurrentUser
          
          #Get-ChildItem

          Write-Host "Connect to Microsoft Entra ID"
                    
          $SecuredPassword = ConvertTo-SecureString -String "$env:AppSec" -AsPlainText -Force
          $ClientSecretCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "$env:AppId", $SecuredPassword
          Connect-MgGraph -TenantId "$env:TenantId" -ClientSecretCredential $ClientSecretCredential -NoWelcome
          
          Write-Host "USERS:"
          Get-MgUser -Property "id,displayName" -PageSize 5 | Format-Table DisplayName, Id

          Import-Module Microsoft.Graph.Identity.SignIns

          Write-Host "Get-InstalledModule"
          Get-InstalledModule | Format-Table -Property Version, Name, Repository

          Write-Host "Get-MgBetaIdentityConditionalAccessPolicy"
          Get-MgBetaIdentityConditionalAccessPolicy
          
          Write-Host "Loading the PowerShell script"
          . .\ConditionalAccessPolicy.ps1

          Write-Host "Runnin the PowerShell script"
          Add-ConditionalAccessPolicy -PolicyName "Woodgrove demo - sign in risk" -AppId ${{ env.WebAppId }}
          
          Write-Host "Disconnect from Microsoft Entra ID"
          Disconnect-MgGraph  | Out-Null


        
